Programmers-Coach-Coach/Coach-Coach-client

- index.html
- package-lock.json
- package.json
- src/App.tsx
- src/__tests__/__snapshots__/theme.test.ts.snap
- src/__tests__/theme.test.ts
- src/style/global.ts
- src/style/theme.ts
- global 스타일 설정
- theme 설정
- 레이아웃이 알맞게 설정되어있는지
- ![image](https://github.com/user-attachments/assets/7e6628b8-190f-4e0b-b9a3-9c60fc739adc)
closed #6
> Feat : glabal 스타일링 및 테마 설정

- src/__tests__/theme.test.ts
- theme.test.ts 수정
- test.each()를 사용해서 리팩토링
- theme.test.ts 파일의 각 요소의 테스트 부분
closed #9
> Refactor: theme.test.ts 수정

- index.html
- index.html 수정
- index.html 파일에 rel="preload" 속성 추가
closed #11
> Refactor: 웹폰트 최적화

- src/App.tsx
- src/style/global.ts
- global.ts 수정 (body에 대한 부분 삭제 및 전체 marin, padding 0으로 설정)
- @font-face 에서 src 속성에 format("font-woff2") 설정
- global.ts에 있던 속성들을 빼고 App.tsx에 styled-component로 옮겨서 작성
closed #14
> Fix: 화면너비 조절 및 폰트 포맷 수정

- src/components/common/CustomButton.tsx
- CustomButton 공통으로 사용할 버튼 컴포넌트 구현
- 스타일 일관성
- 컴포넌트 확장성
closed #20
> Feat: CustomButton 공통 컴포넌트 구현

- package-lock.json
- package.json
- src/App.tsx
- src/components/common/SelectBox.tsx
- 공통 컴포넌트로 사용할 selectBox 구현
- 라이브러리를 사용하다보니 스타일링이 지저분 => 스타일링 부분 잘 봐야함.
closed #22
> Feat: 공통  SelectBox 구현

- package-lock.json
- package.json
- src/App.tsx
- src/components/common/modal/centerModal/CenterModal.tsx
- src/components/common/modal/subModal/SubModal.tsx
- src/components/common/modal/subModal/contents/FooterPicker.tsx
- src/components/common/modal/subModal/contents/RoutinePicker.tsx
- src/constants/assets.ts
- src/constants/assets.tsx
- src/data/modal.ts
- src/hooks/useModal.ts
- src/style/global.ts
- 모달 공통 컴포넌트 제작하였습니다.
- 폴더 구조에 대해 봐주세요. (복잡한 거 같기도...)
- CenterModal.tsx
- SubModal.tsx
- FooterPicker의 schema = "profile:
- FooterPicker의 schema =  "routine"
- RoutinePicker의 schema = "write"
closed #16
> Design: modal 공통 컴포넌트 제작

- src/__tests__/__snapshots__/theme.test.ts.snap
- src/__tests__/theme.test.ts
- src/components/common/CustomButton.tsx
- src/style/theme.ts
- theme.ts 수정
- CustomButton.tsx 수정
- 확장성이 더 좋은 코드를 위해 CustomButton.tsx에서 조건문으로 분기를 하지 않고 theme.ts에서 먼저 나눠 놓고 사용
closed #28
> Refactor: theme.ts, CustomButtom.tsx 수정

- .eslintrc.cjs
- .gitignore
- package-lock.json
- package.json
- src/api/http.ts
- src/api/queryClient.ts
- src/main.tsx
- vite.config.ts
-  react-query, Zustand 설치
- axios 초기 설정 및 프록시
- 일단 axios error 처리는 제외하고 구성하였습니다.
- env 파일은 어디에서 공유하는게 좋을까요?
closed #45
> Feat: http 설정

- index.html
- src/App.tsx
- src/style/global.ts
- 폰트를 가져오는 방식을 변경하여, 폰트를 가져왔습니다.
- 폰트를 이중으로 가져오는 것을 삭제
- index.html의 link 태그
- global.ts의 @font-face
closed #60
> Fix: 폰트를 적용하지 못하는 오류 해결

- vite.config.ts
- 이전에 작업한 vite proxy 설정을 삭제하였습니다.
- 백엔드에서 cors로 localhost:5173 포트를 열어주어서 프록시 설정이 필요가 없어졌습니다.
closed #77
> Remove: vite proxy 삭제

- src/components/coach/CaochListFilter.tsx
- src/components/common/modal/Modal.tsx
- src/components/common/modal/contents/FilterPicker.tsx
- src/constants/assets.tsx
- src/data/sportsList.ts
- src/hooks/useCoachFilter.ts
- src/hooks/useModal.ts
- src/models/coach.model.ts
- src/models/sports.model.ts
- src/pages/CoachList.tsx
- 코치 리스트 필터 UI를 제작하였습니다.
- UI 디자인, 색상 등
https://github.com/user-attachments/assets/2d1ed968-1c57-46c3-86c7-6ec5511e0ea2
closed #95
> Design: 코치 리스트 필터 UI

- src/api/auth.api.ts
- src/api/coach.api.ts
- src/components/mypage/CoachProfileSection.tsx
- src/components/mypage/ProfileSection.tsx
- src/components/signup/SignupForm.tsx
- src/constants/apiPath.ts
- src/constants/assets.tsx
- src/hooks/useAuth.ts
-  useAuth 오타 수정 및 주석 삭제
-  useAuth 오타 수정 및 주석 삭제
closed #104
> Fix: useAuth 오타 수정 및 주석 삭제

- src/components/common/InputField/search/Search.tsx
- src/constants/assets.tsx
- src/pages/CoachList.tsx
- src/pages/Home.tsx
- 검색창 ui 
- MUI를 사용하지는 않았지만, 기존 Input 컴포넌트들과 최대한 비슷하게 만들었습니다.
https://github.com/user-attachments/assets/8a1555dd-81d7-48b5-87d6-80d80e966591
closed #109
> Design: 검색창 ui 구현

- src/App.tsx
- src/api/auth.api.ts
- src/api/coach.api.ts
- src/components/coach/BasicInfo.tsx
- src/components/coach/Coach.tsx
- src/components/coach/DetailInfo.tsx
- src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
- src/components/modal/Review.tsx
- src/components/modal/ReviewInner.tsx
- src/components/mypage/CoachProfileSection.tsx
- src/constants/assets.tsx
- src/data/coachProfile.ts
- src/hooks/queries/useCoachDetail.ts
- src/models/coach.model.ts
- src/pages/Coach.tsx
- src/style/theme.ts
- src/utils/getTitle.ts
- vite.config.ts
- 코치 디테일 UI 제작 및 API 연결
- 리뷰 모달 생성
- 현철님 'ReviewCard' 컴포넌트 수정
- 코치 디테일 UI에서 오픈 카카오톡 링크를 임시로 삭제하였습니다.
- 사용자가 '문의하기'와 '오픈 카카오톡 링크'를 혼동할 수 있다는 생각이 들어서 임시로 삭제  -> 추후에 결정
- ![image](https://github.com/user-attachments/assets/69adb931-caca-4de4-9a4f-47330354bdd5)
closed #119
> Feat/coach detail UI

- src/api/notification.api.ts
- src/components/common/Empty/Empty.tsx
- src/constants/apiPath.ts
- src/hooks/queries/useNotification.ts
- src/pages/Notification.tsx
- 알림 API와 연결하는 작업입니다.
- **백엔드에서 날짜를 보내줄 때 UTC 시간대로 보내주는 것으로 통일하였고, 프론트에서 현재 시간으로 변경합니다.**
closed #147
> Feat: 알림 API 연결

- src/api/auth.api.ts
- src/api/http.ts
- src/constants/apiPath.ts
- src/pages/CheckPassword.tsx
- src/store/authStore.ts
- src/utils/login.ts
- src/utils/logoutUtil.ts
- 토큰 재발급 부분
- 401에러 발생시 인터셉터 설정하여 토큰 재발급
- 토큰 재발급 부분
- 401에러 발생시 인터셉터 설정하여 토큰 재발급
- 
closed #152
> Feat: 토큰 재발급 api, 인터셉터 설정

- src/api/notification.api.ts
- src/hooks/queries/useNotification.ts
- src/pages/Notification.tsx
- 알림 전체 삭제 API를 연결합니다.
closed #160
> Feat: 알림 전체 삭제 API 연결

- src/App.tsx
- src/components/common/InputField/dropdown/CategoryDropdown.tsx
- src/components/record/exerciseRecord/ExerciseCalendar.tsx
- src/components/record/exerciseRecord/ExerciseDetail.tsx
- src/data/modal.ts
- src/pages/Record.tsx
- src/pages/RecordDatail.tsx
- 날짜 디테일 페이지 작업
- 해당 날짜를 클릭하면 날짜 디테일 페이지로 이동
- 운동 기록, 신체 기록 표시
- 서버 복구 후 다시 동영상 찍어서 올리겠습니다!
closed #157
> Feat/record detail UI

- src/api/coach.api.ts
- src/hooks/queries/useContact.ts
- src/pages/Coach.tsx
- src/utils/error.ts
- 문의하기 API 연결
- 이미 문의한 코치에 대해서 'toast' 메세지 띄움
- error 유틸 함수 생성 (필요한 에러 코드들 정의해서 쓰는 파일)
closed #162
> Feat: 문의하기 API 연결

- src/api/auth.api.ts
- src/components/layout/PrivateLayout.tsx
- src/components/mypage/AddressSearchField.tsx
- src/components/mypage/CoachProfileSection.tsx
- src/components/mypage/ProfileSection.tsx
- src/constants/apiPath.ts
- src/hooks/useAuth.ts
- src/main.tsx
- src/models/coach.model.ts
- 다음카카오 우편번호 api 사용 부분 수정
- 코치 프로필 수정 기능 구현
- 다음카카오 우편번호 api 사용 부분 수정
- 코치 프로필 수정 기능 구현
closed #164
> Refactor: 프로필 페이지 리팩토링

- src/api/likes.api.ts
- src/components/Icon/IconButton.tsx
- src/components/coach/BasicInfo.tsx
- src/components/coach/Coach.tsx
- src/components/coach/PopularCoaches.tsx
- src/components/common/InputField/CheckBox/Heart.tsx
- src/constants/assets.tsx
- src/data/coachProfile.ts
- src/hooks/queries/useLikes.ts
- src/models/coach.model.ts
- 관심 등록 및 관심 수정 API 연결하는 작업입니다.
- 코치 디테일 페이지에 coachId가 빠져있어, 백엔드에 전달 후 인터페이스에 추가하였습니다.
- 관심 등록 및 삭제 API 연결
https://github.com/user-attachments/assets/83c73900-653d-4d02-bc2a-2e168222806b
closed #173
> Feat: 관심 등록 및 관심 수정 API 연결

- src/api/coach.api.ts
- src/components/coach/CaochListFilter.tsx
- src/components/coach/Coach.tsx
- src/components/coach/CoachList.tsx
- src/components/common/InputField/search/Search.tsx
- src/components/common/modal/contents/FilterPicker.tsx
- src/components/sports/SportsList.tsx
- src/data/sportsList.ts
- src/hooks/useCoachFilter.ts
- src/hooks/useCoachList.ts
- src/models/coach.model.ts
- src/models/sports.model.ts
- src/pages/CoachList.tsx
-  코치 리스트 필터들을 쿼리 스트링으로 추가
-  따라서 기존에 상태에 보관했던 필터 데이터를 쿼리 스트링에서 가져오는 코드로 대체
- 쿼리스트링을 설정하였습니다. 
- ex) sort = "latest"
- ex) sportsIds = 1,2,3
https://github.com/user-attachments/assets/aee81b8d-45e7-4274-b370-0c41b19d99ff
closed #186
> Feat: 코치 리스트 필터들을 쿼리 스트링으로 추가

- src/api/record.api.ts
- src/components/chart/LineChart.tsx
- src/components/modal/PhysicalRecordInner.tsx
- src/components/record/exerciseRecord/ExerciseCalendar.tsx
- src/components/record/exerciseRecord/ExerciseDetail.tsx
- src/components/record/physicalRecord/PhysicalRecord.tsx
- src/components/record/physicalRecord/PhysicalRecordInputs.tsx
- src/constants/apiPath.ts
- src/constants/regex.ts
- src/hooks/queries/useRecord.ts
- src/hooks/useQueryString.ts
- src/models/record.model.ts
- src/pages/Record.tsx
- src/pages/RecordDatail.tsx
- src/utils/format.ts
- API 연결
- 운동 기록 조회
- 기록 디테일 페이지 조회
- 신체 정보 입력, 수정 API 연결
https://github.com/user-attachments/assets/84b34644-9800-4404-ab77-83f835a83816
closed #169
> Feat: 기록 API 연결

- src/api/record.api.ts
- src/components/chart/LineChart.tsx
- src/constants/apiPath.ts
- src/hooks/queries/useRecord.ts
- src/models/record.model.ts
- src/pages/Record.tsx
- src/utils/chart.ts
- 신체 기록 차트 API 연결하는 작업입니다.
- 버그 : chartId === 0 번에 해당하는 weight 데이터를 가져오고, 두번째 가져올 때 차트의 높이가 줄어듬
- 이유를 못찾겠어서, 이후에 작업하겠습니다!
https://github.com/user-attachments/assets/b2cb64ae-b548-416b-b408-490a4e045153
closed #189
> Feat: 신체 기록 차트 API 연결

- src/components/common/Header/DetailHeader.tsx
- src/components/common/Header/LogoHeader.tsx
- src/components/common/InputField/CheckBox/Heart.tsx
- src/hooks/queries/useLikes.ts
- src/utils/getTitle.ts
- 기존의 뒤로가기 클릭 시 navigate(-1)로 이동했음 => 상태도 되돌리는 오류 발견
- 따라서 직접 주소를 입력하여 이동하도록 설정
closed #192
> Refactor: 뒤로가기 연결하는 방식을 변경

- src/components/common/Empty/Empty.tsx
- src/components/common/InputField/dropdown/CategoryDropdown.tsx
- src/components/record/exerciseRecord/ExerciseCalendar.tsx
- src/components/record/exerciseRecord/ExerciseDetail.tsx
- src/components/routine/Action.tsx
- src/pages/RecordDatail.tsx
- 스탬프 크기 등 기록 페이지 관련 UI 변경
- 공통 빈 화면 컴포넌트 변경
- 기록페이지의 드롭다운에는 체크박스를 모두 true로 변경
closed #194
> Refactor: 기록 페이지 관련 UI 변경

- src/components/Icon/IconButton.tsx
- src/components/coach/CaochListFilter.tsx
- src/components/coach/CoachList.tsx
- src/components/common/InputField/search/Search.tsx
- src/hooks/useQueryString.ts
> Feat: 검색창 연결

- package-lock.json
- package.json
- src/components/chart/LineChart.tsx
- src/components/modal/PhysicalRecordInner.tsx
- src/components/record/physicalRecord/PhysicalRecord.tsx
- src/components/record/physicalRecord/PhysicalRecordInputs.tsx
- src/hooks/queries/useRecord.ts
- 신체 기록 인풋의 타입을 number로 변경
- for문에서 key값이 같아서 재렌더링이 되지 않는 오류를 uuid를 사용하여 해결
- for문에서 key값이 같아서 재렌더링이 되지 않는 오류를 uuid를 사용하여 해결
closed #203
> Bug: 차트 관련 버그 수정

- src/api/http.ts
- src/components/mypage/CoachProfileSection.tsx
- src/hooks/queries/useFetchCoachProfile.ts
- src/hooks/useFetchAuth.ts
- src/models/auth.model.ts
- src/utils/genderUtils.ts
- 마이페이지 리팩토링
- 코치일떄와 아닐때의 분기 처리
- 마이페이지 리팩토링
- 코치일떄와 아닐때의 분기 처리
closed #204
> Refactor: 마이페이지 리팩토링

- src/components/Profile/ProfileList/InqueryCoachProflieList.tsx
- src/components/Profile/ProfileList/InquiryProfileList.tsx
- src/components/Profile/ProfileList/MatchingProfileList.tsx
- src/components/Profile/ProfileList/MyCoachesProfileList.tsx
- src/components/common/Footer/Footer.tsx
- src/components/routine/RoutineList.tsx
- src/constants/assets.tsx
- src/pages/Notification.tsx
- 아이콘 색상 및 종류 변경
- 아이콘 색상 및 종류 변경
closed #209
> Refactor: 아이콘 색상 및 종류 변경

- src/components/coach/CaochListFilter.tsx
- src/components/record/exerciseRecord/ExerciseCalendar.tsx
- src/pages/Coach.tsx
- src/pages/Notification.tsx
- src/pages/Routine/MemberRoutine.tsx
- src/pages/Routine/MyRoutine.tsx
- src/pages/Routine/RoutineDetail.tsx
- src/style/theme.ts
- 카카오 링크 버튼 추가 
- 추가하기, 리뷰 쓰기 같은 버튼의 색상, 사이즈를 통일
closed #206
> Feat: 카카오톡 링크 디테일 페이지에 표시

- src/components/Icon/Icon.tsx
- src/components/common/Footer/Footer.tsx
- src/constants/assets.tsx
- src/hooks/queries/useLikes.ts
- src/pages/Signup.tsx
- 푸터 이미지 변경하였습니다. 또한 현재 페이지에 색상을 변경하였습니다!
closed #
> Feat: 푸터 이미지 변경

- src/components/coach/DetailInfo.tsx
- src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
- src/components/common/InputField/search/Search.tsx
- src/components/modal/ReviewInner.tsx
- search가 빈값도 요청할 수 있도록 수정
- search가 같은 값일 때 2번 요청보내지 않음 -> query string이라서!
closed #215
> Feat: search가 빈값도 요청할 수 있도록 수정

- src/components/chart/LineChart.tsx
- src/components/coach/CoachList.tsx
- src/components/common/Footer/Footer.tsx
- src/hooks/queries/useNotification.ts
- src/pages/Home.tsx
- src/pages/Notification.tsx
- 알림 삭제하면 바로 알림 개수에 반영되도록 auth 호출
- 에러거나 코치 리스트 없을 때 UI 추가
closed #217
> Feat:알림 삭제하면 바로 알림 개수에 반영되도록 auth 호출

- src/components/coach/BasicInfo.tsx
- src/components/mypage/CoachProfileSection.tsx
- src/hooks/queries/useContact.ts
- src/pages/Coach.tsx
- src/pages/Home.tsx
- src/pages/MyCoach.tsx
-  매칭 신청 시 토스트 알림
- 로그 제거 및 사용하지 않는 주석 삭제
(1) 카카오톡 문의하기
(2) 매칭 신청하기
로 문구 변경
closed #219
> Remove: 로그 제거

- src/components/mypage/CoachProfileSection.tsx
- 코치 프로필 리팩토링
- 코치 프로필 리팩토링
closed #222
> Refactor: 코치 프로필 리팩토링

- src/components/coach/Coach.tsx
- src/components/coach/PopularCoaches.tsx
- src/components/sports/SportsList.css.ts
- src/components/sports/SportsList.tsx
- 홈 UI 리팩토링
- 스크롤 가능하고, 웹 뷰일 때 해당 카드 링크로 이동해버리는 문제가 있어서 왼, 오 버튼 추가
closed #
> Feat: 홈 UI 리팩토링

- src/components/layout/Layout.tsx
- src/components/mypage/CoachProfileSection.tsx
- src/hooks/useAuth.ts
- src/pages/Login.tsx
- src/store/authStore.ts
- 로그인 페이지 헤더 삭제
- 로그인 전역 상태 새로고침시 초기화되는 문제 수정
- 로그인 페이지 헤더 삭제
- 로그인 전역 상태 새로고침시 초기화되는 문제 수정
closed #227
> Refactor: 로그인 페이지 및 로그인 전역상태 리팩토링

- src/hooks/useMember.ts
- src/pages/ManageMember.tsx
- 코치가 아닌 경우 매칭 회원리스트 페이지 변경
- 코치가 아닌 경우 매칭 회원리스트 페이지 변경
closed #213
> Refactor: 코치가 아닌 경우 매칭 회원리스트 페이지 변경

- src/components/chart/LineChart.tsx
- src/components/common/InputField/CheckBox/Heart.tsx
- src/hooks/queries/useLikes.ts
- src/hooks/queries/useNotification.ts
- src/hooks/queries/useRecord.ts
- src/utils/chart.ts
- src/utils/sort.ts
- 알림 내림차순 정렬
- 좋아요 성공하지 않아도 UI에서 낙관적인 업데이트로 하트가 채워지는 현상 방지
closed #231
> Fix: 알림 정렬

- src/components/mypage/CoachProfileSection.tsx
- src/pages/ManageMember.tsx
- 매칭 회원 리스트 페이지 리팩토링
- 코치 프로필 default값 변경
- 매칭 회원 리스트 페이지 리팩토링
- 코치 프로필 default값 변경
closed #230
> Refactor: 매칭 회원페이지 및 코치프로필 리팩토링

- src/api/review.api.ts
- src/components/Icon/IconButton.tsx
- src/components/card/NotificationCard.tsx
- src/components/coach/Coach.tsx
- src/components/coach/DetailInfo.tsx
- src/components/coach/PopularCoaches.tsx
- src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
- src/components/common/InputField/CheckBox/Heart.tsx
- src/components/modal/ReviewControl.tsx
- src/components/modal/ReviewInner.tsx
- src/components/mypage/CoachProfileSection.tsx
- src/components/mypage/ProfileSection.tsx
- src/components/record/exerciseRecord/ExerciseDetail.tsx
- src/components/routine/Routine.tsx
- src/data/coachProfile.ts
- src/hooks/queries/useCoachDetail.ts
- src/hooks/queries/useContact.ts
- src/hooks/queries/useReview.ts
- src/hooks/useDropdownClick.ts
- src/models/coach.model.ts
- src/pages/Coach.tsx
- 리뷰 변경, 삭제
- 이미 신청하거나 매칭이 완료된 코치는 버튼 diabled
closed #
> Feat: 리뷰 변경, 삭제

- src/components/mypage/CoachProfileSection.tsx
- 코치프로필 404에러 수정
- 코치프로필 404에러 수정
closed #244
> Fix: 코치프로필 404에러 수정

- src/App.tsx
- src/components/Profile/Profile.tsx
- src/components/coach/BasicInfo.tsx
- src/components/coach/CaochListFilter.tsx
- src/components/coach/CoachList.tsx
- src/components/coach/DetailInfo.tsx
- src/components/common/Footer/Footer.tsx
- src/components/common/Header/DetailHeader.tsx
- src/components/common/InputField/Text/InputInModal.tsx
- src/components/common/InputField/dropdown/CategoryDropdown.tsx
- src/components/common/modal/Modal.tsx
- src/components/mypage/ProfileSection.tsx
- src/components/record/exerciseRecord/ExerciseDetail.tsx
- src/pages/Coach.tsx
- src/style/global.ts
- src/style/theme.ts
- 각종 디자인 수정 (Commit) 확인
closed #243
> Fix: 각종 디자인 수정

- src/components/layout/Layout.tsx
- src/components/mypage/ProfileSection.tsx
- src/components/signup/SignupForm.tsx
- src/pages/Login.tsx
- src/pages/Mypage.tsx
- src/style/theme.ts
- 전반적인 리팩토링
- 전반적인 리팩토링
closed #248
> Refactor: 전반적인 리팩토링

- src/components/coach/BasicInfo.tsx
- src/components/coach/Coach.tsx
- src/components/coach/DetailInfo.tsx
- src/components/common/modal/Modal.tsx
- 리뷰 '리뷰 작성' 안보이게 
- 디테일 페이지 UI 수정
closed #247
> Fix: 리뷰와 UI 디자인 수정

- src/components/coach/DetailInfo.tsx
- src/components/common/InputField/dropdown/CategoryDropdown.tsx
- src/models/record.model.ts
- 리뷰 추가 버튼 나타나는 조건에 '내가 아닐 때'를 '나일 때'로 잘 못 적은 코드 ㅅ정
closed #이슈번호
> Fix: 리뷰 추가 버튼 조건 버그 수정

- src/components/coach/CoachList.tsx
- src/components/coach/DetailInfo.tsx
- src/components/common/Card/ReviewCard.tsx/ReviewCard.tsx
- src/pages/Coach.tsx
- src/pages/CoachList.tsx
- src/pages/ManageMember.tsx
- src/pages/MyCoach.tsx
- src/pages/Notification.tsx
- src/pages/Record.tsx
- src/pages/RecordDatail.tsx
- src/pages/Routine/CoachRoutine.tsx
- src/pages/Routine/MemberRoutine.tsx
- src/pages/Routine/MyRoutine.tsx
- src/pages/Routine/RoutineDetail.tsx
-현철님이 스크롤 문제로 전체를 감싸는 Layout에 마진을 제거해서 밑이 잘리는 문제가 생겼음
=> 모든 페이지에 WhiteSpace height = 60px를 추가하여 마진 넣어줌
closed #이슈번호
> Refactor: 모든 마진 바텀 추가

- src/components/mypage/CoachProfileSection.tsx
- src/pages/Mypage.tsx
- 코치 프로필 취소버튼 삭제
- 코치 프로필 취소버튼 삭제
closed #259
> Refactor: 코치 프로필 취소버튼 삭제

- src/components/coach/DetailInfo.tsx
- 코치 디테일 자기소개 글 넘치는 것 수정
- 코치 디테일 자기소개 글 넘치는 것 수정
closed #263
> Refactor: 코치 디테일 자기소개 글 넘치는 것 수정

- src/pages/CheckPassword.tsx
- src/pages/ManageMember.tsx
- src/pages/Mypage.tsx
- 전체적인 UI 패딩 조정
- 전체적인 UI 패딩 조정
closed #266
> Refactor: 전체적인 UI 패딩 조정

- src/components/card/NotificationCard.tsx
- src/hooks/queries/routine/useAction.ts
- src/hooks/queries/routine/useCategory.ts
- src/hooks/queries/routine/useRoutine.ts
- src/hooks/queries/useNotification.ts
- src/hooks/useMember.ts
- console.log, console. error 삭제
- console.log, console. error 삭제 후 throw
closed #이슈번호
> Refactor: Remove Console log & error

- src/components/mypage/CoachProfileSection.tsx
- 코치 전용 프로필 이미지 크기 조정
- 코치 전용 프로필 이미지 크기 조정
closed #270
> Refactor: 코치 전용 프로필 이미지 크기 조정

- package-lock.json
- package.json
- src/components/card/NotificationCard.tsx
- src/components/coach/PopularCoaches.tsx
- src/components/common/modal/contents/ActionModalInner.tsx
- src/components/sports/SportsList.css.ts
- src/components/sports/SportsList.tsx
- src/style/theme.ts
- lazyloading 외 다양한 디자인 수정
- 커밋 메세지 참고
- 우선 lazyloading은 메인화면과 종목 리스트에만 적용했고, 나머지는 나중에 작업해놓을게요!
closed #이
> Refactor: lazyloading 외 다양한 디자인 수정

- src/components/common/InputField/Text/InputInModal.tsx
- src/components/common/InputField/Text/InputNumberInModal.tsx
- src/components/common/modal/Modal.tsx
- src/components/common/modal/contents/RoutineContents.tsx
- Fix: 모바일에서 Footer Modal 가려짐 & Refactor: placeholder 각 다르게 설정
- 모바일 환경 : Footer Modal
- placeholder
closed #이슈번호
> Fix: 모바일에서 Footer Modal 가려짐 & Refactor: placeholder 각 다르게 설정

- src/components/common/modal/Modal.tsx
- Fix: Footer Modal
- Footer Modal
closed #이슈번호
> Fix: Footer Modal

- src/components/coach/PopularCoaches.tsx
- 인기있는 코치의 description을 자동으로 늘어나게 설정
- 나머지 이슈는 나중에 작업
> Fix: 인기있는 코치의 description을 자동으로 늘어나게 설정

- src/components/common/InputField/Text/InputInModal.tsx
- src/components/routine/Action.tsx
- src/hooks/queries/routine/useAction.ts
- src/hooks/queries/routine/useCategory.ts
- src/hooks/queries/routine/useRoutine.ts
- src/hooks/useMember.ts
- 운동 가이드 45자 늘림, 운동 가이드 두 줄로 보임
- 운동 가이드
closed #이슈번호
> Refactor: 운동 가이드 description

- src/components/mypage/ProfileSection.tsx
- src/pages/Home.tsx
- 이미지 확장자 추가
- 이미지 확장자 추가
closed #286
> Refactor:이미지 확장자 추가

- src/pages/Home.tsx
- 메인화면 padding 조절
- 메인화면 padding 조절
closed #289
> Refactor: 메인화면 padding 조절

- src/components/common/modal/Modal.tsx
- center modal이 Footer에 가려지는 것 수정
- Footer Modal, Center Modal
closed #이슈번호
> Fix: center modal

- src/api/http.ts
- src/components/mypage/CoachProfileSection.tsx
- http 및 코치프로필 모달 수정
- http 및 코치프로필 모달 수정
closed #299
> Refactor: http 및 코치프로필 모달 수정

- index.html
- 타이틀 코치코치로 변경
- 타이틀 코치코치로 변경
closed #301
> Refactor: 타이틀 코치코치로 변경

- README.md
- 개발 포인트의 트렁크 기반 전략 추가
closed #이슈번호
> Docs: 개발 포인트의 트렁크 기반 전략 추가

- package-lock.json
- package.json
- src/components/mypage/ProfileSection.tsx
- 이미지 최적화 (이미지 webp 형식으로 변환)
-이미지 최적화 (이미지 webp 형식으로 변환)
closed #314
> Refactor: 이미지 최적화

- src/components/mypage/ProfileSection.tsx
- 유저 프로필 로그 삭제
- 유저 프로필 로그 삭제
closed #317
> Refactor: 유저 프로필 로그 삭제

- src/components/coach/CoachList.tsx
- src/hooks/useCoachFilter.ts
- src/hooks/useDebounce.ts
- 디바운스 훅 생성
- 코치 리스트 페이지에서 ```정렬순```과 ```종목``` 을 선택하여 API를 호출하는데, 디바운스 적용
- 정렬 순  (택 1) : 300ms
- 종목 선택 (택 여러개) : 500ms
https://github.com/user-attachments/assets/a1f2e78d-9c9a-44dd-af71-162c820e6e78
closed #110
> Feat: 디바운스 적용

- src/components/login/LoginForm.tsx
- src/pages/TotalLogin.tsx
- 카카오, 구글 소셜로그인 구현
- 카카오, 구글 소셜로그인 구현
closed #335
> Feat : 카카오, 구글 소셜로그인 구현

- package-lock.json
- package.json
- src/components/mypage/CoachProfileSection.tsx
- src/components/mypage/ProfileSection.tsx
- 코치프로필 문의가능시간 수정
- 코치프로필 문의가능시간 수정
closed #338
> Refactor: 코치프로필 문의가능시간 수정

- src/components/common/InputField/Select/SportSelectBox.tsx
- 관심, 코칭 종목 개수 제한
- 코치프로필, 내 프로필 SportSelectBox 컴포넌트
closed #343
> Refactor: 관심, 코칭 종목 개수 제한

- src/components/common/Footer/Footer.tsx
- src/components/common/Header/LogoHeader.tsx
- src/pages/First.tsx
- src/pages/Mypage.tsx
> Refactor: 전체적인 url 및 UI 수정

- src/components/Profile/MemberProfile.tsx
- src/components/Profile/ProfileList/SliderProfileList.tsx
- src/pages/Routine/MemberRoutine.tsx
- src/pages/Routine/MyMember.tsx
- src/utils/formatDate.ts
- 회원 정렬, 날짜, 종목 색, 선택
closed #375
> Feat: 회원 UI 기능

- src/components/Profile/CoachProfile.tsx
- src/components/card/NotificationCard.tsx
- src/components/common/Footer/Footer.tsx
- src/components/record/exerciseRecord/ExerciseDetail.tsx
- src/components/routine/RecordRoutine.tsx
- src/components/routine/RecordRoutineList.tsx
- src/models/notification.model.ts
- src/models/record.model.ts
- src/pages/Coach.tsx
- src/pages/Notification.tsx
- src/pages/RecordDatail.tsx
> Feat: 알림 조회 및 기록 UI 연결

- src/components/coach/Introduction.tsx
- src/constants/apiPath.ts
- src/constants/filter.ts
- url 오타 수정
- review 오타 수정
closed #381
> Fix: 오타 수정

- src/components/common/InputField/Text/CommonInput.tsx
- src/components/mypage/AddressSearchField.tsx
- src/components/mypage/CoachProfileSection.tsx
- src/hooks/queries/useFetchCoachProfile.ts
> Refactor: 코치프로필 에러 수정

- src/pages/Mypage.tsx
> Refactor: UI수정

- src/components/coach/CoachDetails.tsx
- src/components/coach/Introduction.tsx
- src/pages/CoachList.tsx
- 코치 UI 수정
- 코치 UI 수정
closed #393
> Refactor : 코치 UI 수정

- src/components/coach/detail/Introduction.tsx
- 코치 자기소개 텍스트 줄바꿈 처리
- 자기소개 텍스트 줄바꿈(\n)을 화면이 인식할 수 있도록 white-space: pre-line css 적용
- 가독성을 위한 텍스트 포멧팅 적용
| Pre-line 적용 전                                                                                  | Pre-line 적용 후                                                                                   |
|---------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| ![image](https://github.com/user-attachments/assets/0f014a21-1e75-4bf8-bf8d-73111c45003f)        | ![image](https://github.com/user-attachments/assets/d30f7bae-1b79-4e54-95b8-6dbe9b1c4fb0)        |
closed #404
> Style: 자기소개 텍스트 줄바꿈 처리
